language: python
python:
 - "3.4"
install:
 - pip install -r requirements.txt
 - pip install -r tests/requirements.txt
 - pip install codecov
script:
 - cp settings.py.example settings.py
 - python3 -m pytest --cov-report xml --cov=app --cov=poll
after_success:
 - codecov
